function AIInterviewPrepCard({ analysis }) {
  if (!analysis) return null

  const result = analysis.result || analysis
  const sourceLabel =
    result.source === 'demo' ? 'Demo interview prep' : 'Generated by AI'

  const sections = [
    { title: 'Focus Areas', items: result.focusAreas },
    { title: 'Technical Questions', items: result.technicalQuestions },
    { title: 'Behavioral Questions', items: result.behavioralQuestions },
    { title: 'Project Talking Points', items: result.projectTalkingPoints },
    { title: 'Study Plan', items: result.studyPlan },
  ]

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div>
        <p className="text-sm font-semibold uppercase tracking-[0.16em] text-emerald-600">
          AI Interview Prep
        </p>
        <span className="mt-3 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
          {sourceLabel}
        </span>
        <h2 className="mt-2 text-2xl font-bold text-slate-900">
          Prep plan for this role
        </h2>
        <p className="mt-2 text-sm leading-6 text-slate-600">
          {result.closingAdvice}
        </p>
      </div>

      <div className="mt-6 grid gap-4 md:grid-cols-2">
        {sections.map((section) => (
          <div key={section.title} className="rounded-xl bg-slate-50 p-4">
            <h3 className="text-sm font-bold text-slate-900">{section.title}</h3>
            {section.items?.length > 0 ? (
              <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">
                {section.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            ) : (
              <p className="mt-3 text-sm text-slate-500">No items found.</p>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

export default AIInterviewPrepCard
