function AIJobMatchCard({ analysis }) {
  if (!analysis) return null

  const result = analysis.result || analysis
  const sourceLabel =
    result.source === 'demo' ? 'Demo analysis' : 'Generated by AI'

  const sections = [
    { title: 'Matching Skills', items: result.matchingSkills },
    { title: 'Missing Skills', items: result.missingSkills },
    { title: 'Strengths', items: result.strengths },
    { title: 'Improvements', items: result.improvementSuggestions },
    { title: 'Application Advice', items: result.applicationAdvice },
  ]

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.16em] text-sky-600">
            AI Fit Analysis
          </p>
          <span className="mt-3 inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
            {sourceLabel}
          </span>
          <h2 className="mt-2 text-2xl font-bold text-slate-900">
            Resume match score
          </h2>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            {result.summary}
          </p>
        </div>

        <div className="rounded-2xl bg-slate-900 px-5 py-4 text-center text-white">
          <p className="text-3xl font-black">{result.matchScore}</p>
          <p className="text-xs font-medium text-slate-300">out of 100</p>
        </div>
      </div>

      <div className="mt-6 grid gap-4 md:grid-cols-2">
        {sections.map((section) => (
          <div key={section.title} className="rounded-xl bg-slate-50 p-4">
            <h3 className="text-sm font-bold text-slate-900">{section.title}</h3>
            {section.items?.length > 0 ? (
              <ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">
                {section.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            ) : (
              <p className="mt-3 text-sm text-slate-500">No items found.</p>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}

export default AIJobMatchCard
